### ISSUE TITLE
Changing Default Credentials

### ISSUE THREAD

**Issue by xyker** [rundeck/docker-zoo#10]
Currently the default credentials are admin/admin.  Are there options to change this?

**Comment by lightarrow** [comment]
Fire up jetty you can sub admin in.

$ java -jar rundeck-3.4.0-20210614.war --encryptpwd Jetty
Required values are marked with: *
Username (Optional, but necessary for Crypt encoding):
xyker    <-----Type this value
*Value To Encrypt (The text you want to encrypt):
xyker     <-----Type this value

==ENCRYPTED OUTPUT==
obfuscate: OBF:1xfd1zt11uha1ugg1zsp1xfp
md5: MD5:a029d0df84eb5549c641e04a9ef389e5
crypt: CRYPT:jsnDAc2Xk4W4o




Configuration 

add this to the realm.properties file. 

xyker MD5:a029d0df84eb5549c641e04a9ef389e5,user,admin

**Comment by fdevans** [comment]
It is also possible to volume over the `realm.properties` file with your own version of that, by mounting a volume over the `/home/rundeck/server/config/realm.properties` path.  This is (somewhat briefly) mentioned in the docs https://docs.rundeck.com/docs/administration/configuration/docker.html#user-authentication

**Comment by chendelin1982** [comment]
If use Docker, any environment for username or password?
