### ISSUE TITLE
where is Dockerfile of rundeck

### ISSUE THREAD

**Issue by changsijay** [rundeck/docker-zoo#11]
https://hub.docker.com/r/rundeck/rundeck

maybe can release the Dockerfile for people to change and build it manually?
(if there is no people taking care issues in this repo.)

**Comment by ltamaster** [comment]
Hi @changsijay 
Have you checked this?
https://github.com/rundeck/docker-zoo/blob/master/config/Dockerfile

Luis

**Comment by changsijay** [comment]
@ltamaster this is not Dockerfile of rundeck image.
It is an example how to use rundeck image.

**Comment by changsijay** [comment]
For example, the latest rundeck image is rundeck:3.1.2
But there is no Dockerfile for this image.

**Comment by ProTip** [comment]
Hi @changsijay 

The Docker build is located here: https://github.com/rundeck/rundeck/tree/master/docker/official
