### ISSUE TITLE
Missing variable for Oracle database

### ISSUE THREAD

**Issue by fblettner** [rundeck/docker-zoo#24]
The setup inside the docker image for Oracle is not complete, you should add the environment variable below. If not you will encountered disconnection from the database and errors inside rundeck like this one :
 Caused by: org.hibernate.exception.GenericJDBCException: could not prepare statement

Variable to add into the docker-compose.yml :
RUNDECK_DATABASE_VALIDATIONQUERY: SELECT 1 FROM DUAL

Franck

**Comment by fdevans** [comment]
This is included in #29
