### ISSUE TITLE
set quartz.threadPool.threadCount

### ISSUE THREAD

**Issue by changsijay** [rundeck/docker-zoo#3]
Hi, I am using rundeck container now, and I changed `quartz.threadPool.threadCount` in `rundeck-config.properties`.
However it seems every time container restart will overwrite the config.
Is there any way to set `quartz.threadPool.threadCount`?

**Comment by bobweaddabbitsaboi** [comment]
I have run into this same issue when mounting the config directory on the docker host. docker logs <containername> output for the container shows that it is overwritten at startup.

[0000]  INFO remco[17]: target config has been updated config=/home/rundeck/server/config/rundeck-config.properties resource=rundeck-config.properties.toml

Perhaps there are environment variables that should be used?

**Comment by sdmorel** [comment]
I see there is a specific template to configure `quartz.threadPool.threadCount`, see: https://github.com/rundeck/rundeck/blob/main/docker/official/remco/templates/rundeck-config-quartz.properties
The way you use it is setting up an environment variable on the container with the name corresponding to `"/rundeck/quartz/threadpool/threadcount"`, in this case it should be `RUNDECK_QUARTZ_THREADPOOL_THREADCOUNT` and the value for the `threadCount`

**Comment by fdevans** [comment]
Correct!
