### ISSUE TITLE
change rundeck-config 

### ISSUE THREAD

**Issue by ibaboo** [rundeck/docker-zoo#5]
Hi 

I am testing you docker image which is great. I would like to know if it is possible to change configs in rundeck-config via a docker environment variable?

For now I am trying to change "rundeck.projectsStorageType=db"
to rundeck.projectsStorageType=filesystem

Any suggestions ? I want to avoid building  a new docker image

**Comment by ProTip** [comment]
Hi @ibaboo ,

Yes this is possible. Please see my reply in https://github.com/rundeck/rundeck/issues/4437 .

I hope this helps.
