### ISSUE TITLE
Question Regarding Persistent Storage

### ISSUE THREAD

**Issue by dhandley12** [rundeck/docker-zoo#8]
When using the rundeck docker image, https://hub.docker.com/r/rundeck/rundeck, Is it currently only possible to use a database for persistent storage with a rundeck pro licence? I see an example at the following link but it references a licence key volume as well. 

https://github.com/rundeck/docker-zoo/blob/master/mysql/docker-compose.yml

Thanks!

**Comment by ltamaster** [comment]
Hi @dhandley12,

the external DB works using the OSS image, you can just comment that license line.

Luis

**Comment by dhandley12** [comment]
Awesome, thanks for the confirmation!
