### ISSUE TITLE
Plugins 

### ISSUE THREAD

**Issue by h4wkmoon** [rundeck/docker-zoo#9]
Hi,
How can I install plugins, plz  ?
They are supposed to be located in a folder which is not a volume.

Best regards,
Fred.

**Comment by vjanssens** [comment]
The code contains an example on how to add plugins to a Rundeck instance running in Docker (although it lacks a bit in documentation on what needs to be configured).

Please check https://github.com/rundeck/docker-zoo/tree/master/config.

Notice this line in the Dockerfile: https://github.com/rundeck/docker-zoo/blob/349887655701721166cb1b2be9044309d02f8d8a/config/Dockerfile#L5

And hese lines in docker-compose.yml: https://github.com/rundeck/docker-zoo/blob/349887655701721166cb1b2be9044309d02f8d8a/config/docker-compose.yml#L10-L11

**Comment by fdevans** [comment]
There is also an example on our Welcome Project.  Setup a folder where you keep your plugins and copy them in with the build.

https://github.com/rundeckpro/welcome-project/blob/95c6970c1a558f9fcb0ececb684d30242b6bc137/rundeck/Dockerfile#L10
